=pod

=head1 NAME

Net::OpenNebula - Access OpenNebula RPC interface

=head1 DESCRIPTION

Perl library to access OpenNebula RPC interface.

=head1 SYNOPSIS

 use Net::OpenNebula;
 my $one = Net::OpenNebula->new(
    url      => "http://server:2633/RPC2",
    user     => "oneadmin",
    password => "onepass",
 );
    
 my @vms = $one->get_vms();
 my $vm  = $one->create_vm(
    name     => "the-name",
    template => $template_id
 );
    
 my $state = $vm->state;
 while($state ne "running") {
    sleep 5; # wait 5 seconds for the next request
    $state = $vm->state;
 }
    
 my @nics = $vm->nics;
 my $ip = $nics[0]->ip; # get the ip of the first device

=cut


